In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import time

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import (
    confusion_matrix,
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, LeakyReLU
from tensorflow.keras.optimizers import SGD, RMSprop, Adagrad, Adam, Nadam

In [2]:
df = pd.read_csv("Churn_Modelling.csv")

X = df.iloc[:,3:13].values
Y = df.iloc[:,13].values

In [3]:
labelencoder_x1 = LabelEncoder()
X[:,1] = labelencoder_x1.fit_transform(X[:,1])

labelencoder_x2 = LabelEncoder()
X[:,2] = labelencoder_x2.fit_transform(X[:,2])

In [4]:
X_train, X_test, Y_train, Y_test = train_test_split(
    X,
    Y,
    test_size=0.2,
    random_state=0
)

In [5]:
sc = StandardScaler()

X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [6]:
def build_ann(hidden_layers=3,
              neurons=6,
              activation="relu",
              initializer="uniform",
              optimizer="adam",
              epochs=50,
              batch_size=10,
              dropout_rate=0):

    model = Sequential()

    # First Hidden Layer
    model.add(Dense(
        units=neurons,
        kernel_initializer=initializer,
        activation=activation,
        input_dim=10
    ))

    if dropout_rate > 0:
        model.add(Dropout(dropout_rate))

    # Remaining Hidden Layers
    for i in range(hidden_layers-1):

        model.add(Dense(
            units=neurons,
            kernel_initializer=initializer,
            activation=activation
        ))

        if dropout_rate > 0:
            model.add(Dropout(dropout_rate))

    model.add(Dense(
        units=1,
        kernel_initializer=initializer,
        activation="sigmoid"
    ))

    model.compile(
        optimizer=optimizer,
        loss="binary_crossentropy",
        metrics=["accuracy"]
    )

    start = time.time()

    history = model.fit(
        X_train,
        Y_train,
        validation_split=0.2,
        epochs=epochs,
        batch_size=batch_size,
        verbose=0
    )

    end = time.time()

    predictions = (model.predict(X_test) > 0.5)

    accuracy = accuracy_score(Y_test,predictions)

    precision = precision_score(Y_test,predictions)

    recall = recall_score(Y_test,predictions)

    f1 = f1_score(Y_test,predictions)

    cm = confusion_matrix(Y_test,predictions)

    return {
        "model":model,
        "history":history,
        "accuracy":accuracy,
        "precision":precision,
        "recall":recall,
        "f1":f1,
        "loss":history.history["loss"][-1],
        "val_accuracy":history.history["val_accuracy"][-1],
        "training_time":end-start,
        "confusion_matrix":cm
    }

In [7]:
results = []

for layers in [1,2,3,5]:

    result = build_ann(hidden_layers=layers)

    results.append([
        layers,
        result["accuracy"],
        result["val_accuracy"],
        result["loss"],
        result["training_time"]
    ])

task1 = pd.DataFrame(results,
columns=[
    "Hidden Layers",
    "Accuracy",
    "Validation Accuracy",
    "Loss",
    "Training Time"
])

task1

d:\Ethnotech\Deep Learning\venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.
63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step

d:\Ethnotech\Deep Learning\venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

d:\Ethnotech\Deep Learning\venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step

d:\Ethnotech\Deep Learning\venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

   Hidden Layers  Accuracy  Validation Accuracy      Loss  Training Time
0              1    0.8615             0.850625  0.342970      91.046620
1              2    0.8380             0.833750  0.400086      76.996835
2              3    0.8455             0.828750  0.400522      61.848216
3              5    0.8415             0.828750  0.399773      77.259540

In [8]:
results=[]

for neurons in [4,8,16,32,64]:

    result = build_ann(neurons=neurons)

    results.append([
        neurons,
        result["accuracy"],
        result["loss"],
        result["training_time"]
    ])

task2 = pd.DataFrame(results,
columns=[
    "Hidden Neurons",
    "Accuracy",
    "Loss",
    "Training Time"
])

task2

d:\Ethnotech\Deep Learning\venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

d:\Ethnotech\Deep Learning\venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step

d:\Ethnotech\Deep Learning\venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

d:\Ethnotech\Deep Learning\venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

d:\Ethnotech\Deep Learning\venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

   Hidden Neurons  Accuracy      Loss  Training Time
0               4    0.8420  0.403118      95.654676
1               8    0.8425  0.401129      76.463285
2              16    0.8420  0.393598      88.452139
3              32    0.8525  0.302918      76.780918
4              64    0.8515  0.241745      87.996231